### ISSUE TITLE
Installing `wasm-pack` throws an error saying "The package requires the Cargo feature called `edition2021`, but that feature is not stablized in this version of Cargo (1.56.0-nightly (cc17afbb0 2021-08-02))."

### ISSUE THREAD

**Issue by 0xYao** [LavaMoat/demo-gg20-wasm#75]
- Steps to reproduce

1. Fresh clone the repository.
2. Go into the repository directory and run `cargo install --version 0.10.2 wasm-pack`.
3. The command throws the error described in the title.

- Rust dependencies

```
➜  demo-gg20-wasm git:(wallet) ✗ rustup --version

rustup 1.25.1 (bb60b1e89 2022-07-12)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.56.0-nightly (ccffcafd5 2021-08-11)`
```

- Other relevant information

```
Host OS: M1 Mac Monterrey
VM OS: ARM64 Ubuntu 22.04 (VM in Parallels Desktop)
```

**Comment by 0xYao** [comment]
It worked after deleing the `rust-toolchain` files with "nightly-2021-08-12" in it, e.g. `./rust-toolchain` and `./packages/wasm/rust-toolchain`. 

However, I am getting another error when running `make setup`:

```
error: Did you forget to enable `atomics` and `bulk-memory` features as outlined in wasm-bindgen-rayon README?
  --> /home/parallels/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-rayon-1.0.3/src/lib.rs:15:1
   |
15 | compile_error!("Did you forget to enable `atomics` and `bulk-memory` features as outlined in wasm-bindgen-rayon README?");
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: could not compile `wasm-bindgen-rayon` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
Error: Compiling your crate to WebAssembly failed
Caused by: failed to execute `cargo build`: exited with exit status: 101
  full command: "cargo" "build" "--lib" "--release" "--target" "wasm32-unknown-unknown"
make: *** [Makefile:2: wasm] Error 1
```

It failed with the same error when I ran the command `RUSTFLAGS='-C target-feature=+atomics,+bulk-memory,+mutable-globals' make setup`, i.e. I tried to include the feature flags using the command-line params but it didn't work either.

**Comment by tmpfs** [comment]
What happens if you run the `wasm-pack` command directly in the `packages/wasm` folder?

The cargo config has the required compiler flags: https://github.com/LavaMoat/demo-gg20-wasm/blob/main/packages/wasm/.cargo/config

**Comment by 0xYao** [comment]
<img width="681" alt="image" src="https://user-images.githubusercontent.com/48658585/188525613-4bf06d72-44ee-4ed4-812a-a0af8ad3a2ff.png">

Getting this error on my M1 Mac

**Comment by 0xYao** [comment]
> What happens if you run the `wasm-pack` command directly in the `packages/wasm` folder?

Also the same error as `15 | compile_error!("Did you forget to enable `atomics` and `bulk-memory` features as outlined in wasm-bindgen-rayon README?");` in the Linux VM.

**Comment by tmpfs** [comment]
Ok, so something weird in the Linux VM, not sure what, I had to use an updated LLVM on an M1 and point to that.

I installed LLVM using homebrew and then:

```
# use custom LLVM
export PATH="$BREW_PREFIX/opt/llvm/bin:$PATH"
# hack for building WASM via Rust on M1 chips
export CC=$BREW_PREFIX/opt/llvm/bin/clang
export AR=$BREW_PREFIX/opt/llvm/bin/llvm-ar
``` 

Using clang 13.0.1.

Good luck!

**Comment by 0xYao** [comment]
> Ok, so something weird in the Linux VM, not sure what, I had to use an updated LLVM on an M1 and point to that.
> 
> I installed LLVM using homebrew and then:
> 
> ```
> # use custom LLVM
> export PATH="$BREW_PREFIX/opt/llvm/bin:$PATH"
> # hack for building WASM via Rust on M1 chips
> export CC=$BREW_PREFIX/opt/llvm/bin/clang
> export AR=$BREW_PREFIX/opt/llvm/bin/llvm-ar
> ```
> 
> Using clang 13.0.1.
> 
> Good luck!

Thanks, using the homebrew version of `clang` (arm64) worked. But now I am getting a different error

<img width="576" alt="image" src="https://user-images.githubusercontent.com/48658585/188527322-a2407288-7f10-45d3-8103-260057f88bdb.png">

**Comment by tmpfs** [comment]
Yeh, thats just the `Makefile` being out of date, my bad, it needs some attention after lots of refactoring.

Anywhere you see a `package.json` you will need a `yarn install` to get the dependencies.

**Comment by 0xYao** [comment]
> Yeh, thats just the `Makefile` being out of date, my bad, it needs some attention after lots of refactoring.
> 
> Anywhere you see a `package.json` you will need a `yarn install` to get the dependencies.

Happy to open a PR to address the problems we have discussed in this issue 👍

**Comment by tmpfs** [comment]
> > Yeh, thats just the `Makefile` being out of date, my bad, it needs some attention after lots of refactoring.
> > Anywhere you see a `package.json` you will need a `yarn install` to get the dependencies.
> 
> I'm happy to open a PR to address the problems we have discussed in this issue 👍

Sounds good, nice one 👍

**Comment by 0xYao** [comment]
<img width="536" alt="image" src="https://user-images.githubusercontent.com/48658585/188528161-0c9c9b2c-ee2d-4ec5-b6f7-e52bd1c3a0ac.png">

Getting this issue after `make demo`

**Comment by tmpfs** [comment]
Ok, that package is not published so you will need to `yarn link` it.

**Comment by 0xYao** [comment]
> Ok, that package is not published so you will need to `yarn link` it.

Ummm, I ran `yarn link` in `packages/client` and `yarn link "@metamask/mpc-client"` in the `demo` folder, but it's still giving me the same errors.

**Comment by tmpfs** [comment]
No idea there, as you can see in `package.json` it is using a local `file:` reference to the package. Possibly a problem with the yarn version?

I am using `1.22.17`.

**Comment by 0xYao** [comment]
My yarn version is `1.22.19`, I will check for some examples of how other people are doing `yarn link`.

**Comment by 0xYao** [comment]
> No idea there, as you can see in `package.json` it is using a local `file:` reference to the package. Possibly a problem with the yarn version?

The problem there I had to run `yarn build` inside the `packages/client` folder because the `main` field in `packages/client/package.json` is `dist/index.js`

**Comment by 0xYao** [comment]
Good to see it up and running haha

<img width="589" alt="image" src="https://user-images.githubusercontent.com/48658585/188531524-300cd6c2-b9b4-4f82-9429-3d8c6aec5288.png">

**Comment by 0xYao** [comment]
I will create a PR for these problems tomorrow

**Comment by tmpfs** [comment]
Nice one, sorry for all the rough edges!

**Comment by 0xYao** [comment]
> Nice one, sorry for all the rough edges!

no problem, thank you for creating a great mpc demo example, it's rare to find out in the wild!

**Comment by 0xYao** [comment]
> Nice one, sorry for all the rough edges!

You have any recommendations for productionizing this repo?

**Comment by tmpfs** [comment]
Definitely DO NOT use the snap code as it is.

The websocket server should be fine for production if you can cope with a single point of failure and your users trust the messages to go through a server:

https://docs.rs/mpc-websocket/latest/mpc_websocket/

There is some work in progress on a p2p version using `libp2p` but it is not ready yet.

But for production we really need some clarification on the safe prime issue:

https://github.com/ZenGo-X/multi-party-ecdsa/issues/178

**Comment by 0xYao** [comment]
> Definitely DO NOT use the snap code as it is.
> 
> 
> 
> The websocket server should be fine for production if you can cope with a single point of failure and your users trust the messages to go through a server:
> 
> 
> 
> https://docs.rs/mpc-websocket/latest/mpc_websocket/
> 
> 
> 
> There is some work in progress on a p2p version using `libp2p` but it is not ready yet.
> 
> 
> 
> But for production we really need some clarification on the safe prime issue:
> 
> 
> 
> https://github.com/ZenGo-X/multi-party-ecdsa/issues/178

I asked the ZenGo team for clarification on the issue. 

Btw, what would be the best place to keep in touch with you? Would love to keep the comm open and learn more. 

My email is 0xyao.zh@gmail.com, feel free to drop your telegram contact or something there!
